### ISSUE TITLE
Restarting docker container wipes data

### ISSUE THREAD

**Issue by dannongruver** [PhiTux/DailyTxT#16]
Might be my lack of docker knowledge but restarting the container wipes out all data (registrations, entries, templates). The docker-compose.yml file I use has an external volume so I thought the data would be persistent across restarts.

**Comment by PhiTux** [comment]
This must (well, it should!) be a misconfiguration of your docker...
I've never heard that data gets wiped after restart.

Could you post you yml-file (delete the sensitive data of course!!) - or just show the line of the volume-configuration?
