### ISSUE TITLE
BUG - 500 Server error on /api/search & /api/exportData endpoints after saving a template.

### ISSUE THREAD

**Issue by h3x0x0** [PhiTux/DailyTxT#18]
## Hi @PhiTux, thank you for such an amazing work, is exactly what I was looking for 😮!   +  I would like to support and send you money for coffee or a beer 😃  ##

# Bug Summary and debug video [HERE](https://app.birdeatsbug.com/sessions/JsZ5TTOO9RTaHOTffQSe0CyB7HEfX3pxGnsgyE3IxvZu?consolePaneHiddenGroups=Blocked+Request%26Log&seekSeconds=-0.011&networkPane=true) 

Immediately after saving a template, I am getting a 500  server error for the POST calls on endpoints:
````
/api/search
/api/exportData 
````
### Copy of the response:
````
{"authenticated":true,"message":"An unknown internal server error occured."}
````
### Copy of the response header:
````
HTTP/1.1 500 INTERNAL SERVER ERROR
Server: nginx/1.20.2
Date: Thu, 02 Feb 2023 21:00:37 GMT
Content-Type: application/json
Content-Length: 77
Connection: keep-alive
Access-Control-Allow-Origin: http://127.0.0.1:7777
Vary: Origin
````
####    - When trying to export the data from the settings page, I only get  an export successfully UI message ####
 ####    - Have the bug when using the official docker image docker pull phitux/dailytxt ####
 ####    - Restarting the container won't fix the issue ####
 ####    - Also when running: ####
````
docker run -p 127.0.0.1:<host_port>:8765 -e "PORT=8765" -e "SECRET_KEY=<openssl rand -base64 32>" -e "ALLOW_REGISTRATION=True" -v </save/my/dailytxt-files/here/>:/app/data --name dailytxt -d phitux/dailytxt:latest
````

### The following link includes a screenrecord & the network data feel free to ask if any questions ###

[Debug video with network console enabled and replay on](https://app.birdeatsbug.com/sessions/JsZ5TTOO9RTaHOTffQSe0CyB7HEfX3pxGnsgyE3IxvZu?consolePaneHiddenGroups=Blocked+Request%26Log&seekSeconds=-0.011&networkPane=true)

**Comment by PhiTux** [comment]
Thanks for the awesome feedback! I'll take a look to include some way to support me ;)

Wow, your issue-description is awesome 😀
Especially the video makes it really reproducible! I'll probably take a look into the bug this weekend!

**Comment by Lemon553311-dev** [comment]
You are so awesome!!!!!!!

**Comment by PhiTux** [comment]
Once again, thank you so much, especially for the video! That made it super easy reproducible and I found the bug right away.

See new Version [1.0.11](https://github.com/PhiTux/DailyTxT#1011), where it should be fixed!
Otherwise, please just reopen the issue :)

**Comment by PhiTux** [comment]
@Lemon553311-dev Sorry for not seeing this bug earlier 🙈😅 I remember your issue

**Comment by h3x0x0** [comment]
> You are so awesome!!!!!!!

@Lemon553311-dev   

  #### I'm glad that report covered your bug :heavy_check_mark:  :feelsgood:


:wavy_dash:


:wavy_dash:

> Thanks for the awesome feedback! I'll take a look to include some way to support me ;)
> 
> Wow, your issue-description is awesome 😀 Especially the video makes it really reproducible! I'll probably take a look into the bug this weekend!

#### @PhiTux No, thank you 💯 

#### I figured if you spend days, weeks or months into doing this the least I could do is take an hour to get you the best bug report possible.  This is what I do for a living, I am a QA security engineer & DevSecOps during the day and I audit open source projects for free at night as a way to give back to the community.  I usually setup git burner accounts for OPSEC but please feel free to contact me and I will gladly QA any of your opensource projects for free 🤓

**Comment by PhiTux** [comment]
@h3x0x0 Wow, and that's the awesome community of opensource development that I love 😍 Really cool, that you do that! I was really already wondering how some average person can do such an excellent bug report 😅

**Comment by h3x0x0** [comment]
> @h3x0x0 Wow, and that's the awesome community of opensource development that I love 😍 Really cool, that you do that! I was really already wondering how some average person can do such an excellent bug report 😅

 :wavy_dash:

@PhiTux  Well Marco, on that note some will say I am not that average 😄

Also, the same QA offer goes for testing servers & webapps security related to open source development, that is usually where I help the most since it is my expertise:godmode:

**Comment by PhiTux** [comment]
Thank you very much 🙏
I might come back to your offer in a few month for my other project [schoco](https://github.com/PhiTux/schoco) 😉

**Comment by h3x0x0** [comment]
@PhiTux Btw, you deserve A LOT of credit for responding and fixing the bug!  I will say that for a project that is not being work on a daily basis, releasing a fix in less that 24 hours is outstanding.  

I am very impressed and I been doing this for 17 years, this has been the fastest feedback ⚡ 



> Thank you very much 🙏 I might come back to your offer in a few month for my other project [schoco](https://github.com/PhiTux/schoco) 😉

Just stared it, please do so whenever you are ready!

**Comment by h3x0x0** [comment]
**Telegram** : @permutationum

Please grab it as I am deleting this message in a couple of minutes.  It's easier to reach out that way

**Comment by PhiTux** [comment]
got it ;)

**Comment by PhiTux** [comment]
Hey, 
sadly couldn't reach you via telegram. I would like to invite you to test [schoco](https://github.com/phitux/schoco) 🤗
There's an installation-instruction availabe. I hope it works - it's sadly not that easy to install as many other services...
