### ISSUE TITLE
rename the docker-compose.yml file

### ISSUE THREAD

**Issue by ghajj** [PhiTux/DailyTxT#22]
Renaming the docker-compose.yml file to docker-compose.example would save few keystrokes. Thanks for a a great app.

**Comment by PhiTux** [comment]
Thanks.
Sorry, I don't get it. Why would this save keystrokes?

**Comment by ghajj** [comment]
Maybe because I am a novice git user. When I pull the latest, I don't want to override my custom docker-compose.yml file.
 

    On Monday, March 6, 2023 at 07:31:08 AM PST, Marco Kümmel ***@***.***> wrote:  
 
 


Thanks.
Sorry, I don't get it. Why would this save keystrokes?

**Comment by PhiTux** [comment]
Ok, i understand your problem.
But when using dailytxt, there is no need to clone the whole repo. You can just create a single dir and a docker-compose.yml inside it and paste the content from the docker-compose.yml in this repo. This is the "normal" way to deal with it, i would guess. 

Cloning the whole repo is actually only necessary, when you're actively developing on dailytxt. For this reason I don't see a necessity to rename the template-file to some "unreal" name.
