### ISSUE TITLE
Clearing Searching Field

### ISSUE THREAD

**Issue by surfer-09** [PhiTux/DailyTxT#24]
Hello,
today I installed DailyTxT on my Synology NAS in docker. I already like this tool very much!
One thing which could be improved, is the clearing of the searching result field, when you delete the entered text. The results were also listed when the field is already empty.

Greetings 
surfer ;-)

**Comment by PhiTux** [comment]
Thanks, I'll consider a solution for your idea, once I continue coding on DailyTxT (will take some more month!).

**Comment by PhiTux** [comment]
implemented with next version 319d3ae
