### ISSUE TITLE
Show Version number in Webinterface

### ISSUE THREAD

**Issue by surfer-09** [PhiTux/DailyTxT#25]
Good morning,

another suggestion for DailyTxt: I think it's easy to implement. I couldn't find the version number of the installed version in the web interface. Maybe you could put it there to show, which version you are using?

Thanks!
surfer ;-)

**Comment by PhiTux** [comment]
Yep, that's a good idea! 
As you said: is easy to add ;)

**Comment by PhiTux** [comment]
Implemented in next version 515a524
