### ISSUE TITLE
Arm64 support

### ISSUE THREAD

**Issue by alpe12** [PhiTux/DailyTxT#27]
Can you make it compatible with aarch64? Thanks anyway.

**Comment by PhiTux** [comment]
Hi,
I have already heard of someone in an older issue, who seemed to have it sucessfully working on arm64. 
**Did you already try it? This whould be a really helpful information for others as well!**

If it does not work, then I'll try out buildx to create multi-arch builds including arm64. But I'll still be a few more month until further work on DailyTxT including this multi-arch build...

**Comment by alpe12** [comment]
> Did you already try it?

Yes, with docker-compose.
```
Attaching to dailytxt
dailytxt  | exec /bin/sh: exec format error
dailytxt exited with code 1
dailytxt exited with code 1
dailytxt exited with code 1
```

> But I'll still be a few more month until further work on DailyTxT including this multi-arch build...

No problem. Thanks.

**Comment by Lemon553311-dev** [comment]
Hello I can help!!
I use emulation of amd64 with this command
``docker run --privileged --rm tonistiigi/binfmt --install amd64``
then add ``--platform=linux/amd64`` at the start of your docker run command 
I don't know how to add it to docker-compose file but if you put everything in a single docker run command then you're good to go. 
Sorry I don't have good english but you should understand how it's done. just install that emulation thing and add platform tag

**Comment by PhiTux** [comment]
@Lemon553311-dev Thanks for the information :)

Nevertheless I will try to create multi-arch builds next time!
