### ISSUE TITLE
Bookmark a journal entry

### ISSUE THREAD

**Issue by phrogpilot73** [PhiTux/DailyTxT#31]
First, absolutely love it! Does exactly what I've been looking for, and was using Red Notebook for, only accessible everywhere. 

With that being said, I occasionally make journal entries that I want to share/mention to my wife and/or our couples' therapist. It would be great if you could bookmark an entry, and identify it with a different color icon in the calendar, so I can quickly find the entry that I wanted to bring up/discuss. 

I've tried to search, but sometimes I don't remember exactly the language I used when I type - so simply bookmarking it and quickly being able to go back would be great.

**Comment by PhiTux** [comment]
Thanks for the feedback and the precise feature description. Nice idea to see the bookmark as another color in the calendar.
Will come back to this when I continue programming on DailyTxT.

**Comment by Lemon553311-dev** [comment]
yes yes yes very please! I think there should be a seperate page for it where it lists all bookmarks

**Comment by PhiTux** [comment]
Implemented in next version (see d546b27)
