### ISSUE TITLE
All my Notes are deleted

### ISSUE THREAD

**Issue by neuleo** [PhiTux/DailyTxT#37]
Hi,

I used Dailytxt now for 6 Days and wrote some Things down. Today, I wanted to write today's entry. I wrote it, and midsession, an error appeared: "Failed to save recent_version". The errors disappeared pretty fast, and I didn't think much of it. I finished last day's entry and started writing today's text. Then the website flashed, and out of nowhere, all my notes from the past few days were gone. Just the Text from yesterday (which I wrote today because I forgot yesterday) and the Text for today remain. And I don't know how or if I can restore them. It all worked until today, and I'm pretty sure that I set it all up correctly. I also cannot restore the Text via the "recent changes" Button. It doesn't exist in the other Days. I also looked into the File system where DailyTxT stores my Data. Even in the Files, there are no data for the previous entries

I "installed" DailyTxT on my PC. This means the Project itself runs on my Server and in Chrome, I pressed install DailyTxT, so I could just search DailyTxT and open it in a separate window.

**Comment by PhiTux** [comment]
Hey, I'm really sorry to hear this!
Seems like you've already tested out every way to rescue/restore your text. I don't know what the reason for this to happen was. I've never heard of something like this happening yet...
When even the json-files don't contain any entry for the previous days, then there is no way to restore it! 

There must have been some fatal error when writing the json-files, I guess. I will take a look into the code again, hoping to find the source of the problem.

Things like this should never happen, but they CAN happen. Therefore, you should always use a backup mechanism like rsync/rsnapshot or anything else.

**Comment by PhiTux** [comment]
You probably got the message 'Error on saving new Diary Log', right?

**Comment by neuleo** [comment]
Hi, yes. I already tried everything to restore it but its not possible. I dont know exsactly which error i got. I havent really paid attention to it because i was writing my Text.

I know i cannot provide much Information about this Error but perhaps someone else will have it in the Future (hopefully not) and you already have some information about it.

For me the Loss wasnt fatal. It were only a few Days and i definetly learned my Leason. I will now implement a Way to Backup my Containers.

"Kein Backup, kein Mitleid" (:

**Comment by PhiTux** [comment]
No need to backup the whole containers. Just backup the directories that are mounted to the containers.
