### ISSUE TITLE
Discussion: Resources you used to implement encryption

### ISSUE THREAD

**Issue by iamericfletcher** [PhiTux/DailyTxT#38]
Dear PhiTux,

Apologies for opening this in the issues section, but I don't see a discussion section so am hopeful you'll be able to respond here if possible. 

I'm very grateful to you and the team for this project! I'm reviewing the source code and am learning a whole bunch of stuff. I have a quick question - what resources did you use to implement the encryption for DailyTxT? 

Was it mainly the main docs here - https://cryptography.io/en/latest/

Or did you use other learning resources?

Thank you so much again for taking the time to create such a helpful project :)

Sincerely,
Eric

**Comment by PhiTux** [comment]
Hi Eric,

thanks for the feedback :)

It's long ago that I implemented the encryption-part. But I guess, that it was 50% google and 50% the docs that you just posted 😅

**Comment by iamericfletcher** [comment]
Good to know! The app is very well structured. It's a terrific resource for those wanting to know about things! Bravo and thank you!
