### ISSUE TITLE
Password reset

### ISSUE THREAD

**Issue by adhawkins** [PhiTux/DailyTxT#4]
What's the procedure for resetting a forgotten password in dailytxt? Fortunately I still have an active login, but don't seem to be able to log in again using what I think is my password. The 'change password' option needs me to enter the existing password.

**Comment by PhiTux** [comment]
Yes, that's right. There is actually no option to 'reset'/recover the password! You can only change it, when you're logged in (and still know your old password!).
I did not yet implement any option to recover a password. I'm sorry for that - but that would actually be an important next step to implement...

So there won't be any help for you now, I'm sorry. But you could try to 'brute-force' it...

**Comment by adhawkins** [comment]
Ok, thanks. What I think I'll do then is export the data and then try changing the password. If that doesn't work, I'll start afresh and import the data.

**Comment by PhiTux** [comment]
Yes, export is a good idea. No, I'm sorry - there's not yet an import option :/

**Comment by PhiTux** [comment]
Hi!
The new version, which I just pubilshed (1.0.8), includes an import-option. So in case you successfully exported the data last year, then you can now import it again into your (new!?) account!
And last time you also asked about recovering a password. There's now the new feature of backup codes. They work like one-time passwords, which you can also use to change your password to a new one.

**Comment by adhawkins** [comment]
I managed to recover the password, which was good. Thanks for updating regarding the import and backup codes. Will take a look.
