### ISSUE TITLE
Is that something I have to worry about?

### ISSUE THREAD

**Issue by neuleo** [PhiTux/DailyTxT#41]
https://containercve.com/ shows 36 vulnerabilities with some being Critical
![image](https://github.com/PhiTux/DailyTxT/assets/99101285/d4032e6a-ea4e-4fa8-ab0a-0f19d2686fec)

**Comment by Stokkie64** [comment]
This seems to be due to the outdated base image. I'll see if i can update it quickly

**Comment by neuleo** [comment]
Thank you, keep me updated

**Comment by Stokkie64** [comment]
I updated it but it am getting stuck on my local env. As my new image seems to be unable to access the volumes :( 
But will keep you updated. 

@PhiTux Do you perhaps know why this might happen when i use the dockerfile in the project?

I suspect it's quick for you to do but i would love to be able to help support this cool project.

**Comment by PhiTux** [comment]
Hi,

thanks for your recent information!
I'll try to look into it in the next days! Should be possible over the easter holidays ;)

**Comment by PhiTux** [comment]
Version 1.0.14 is now published.

Updating a project that you haven't worked on for several months is always quite a challenge 😅 I also had quite some trouble to get it working.
containercve.com does no longer show warnings now.
