### ISSUE TITLE
创建失败

### ISSUE THREAD

**Issue by afycn** [PhiTux/DailyTxT#42]
我是准备这样运行的docker run -p 127.0.0.1:8765:8765 -e "PORT=8765" -e "SECRET_KEY=<openssl rand -base64 32>" -e "ALLOW_REGISTRATION=True" -v </save/my/dailytxt-files/here/>:/app/data --name dailytxt -d phitux/dailytxt:latest

但是提示-bash: /save/my/dailytxt-files/here/: No such file or directory

使用编排也是一样

**Comment by Stokkie64** [comment]
Hi, 
I don't understand exactly. 

But i do see your path "/save/my/dailytxt-files/here/" needs to be changed to one that exists on your local file system. 
Are you using windows or Linux?

For linux something like "~/dailytxt/" if you want data stored in your home folder. 

Simplified chinese of above : 您需要将路径设置为计算机上已存在的路径。 上面是linux下的例子。 你用的是windows还是linux？

**Comment by afycn** [comment]
linux   设置成功了

**Comment by Stokkie64** [comment]
Ok Awesome, 
Do you need any other help or can i close this issue?

好的，太棒了，
您需要任何其他帮助吗？或者我可以关闭此问题吗？

**Comment by PhiTux** [comment]
@afycn please write in English on github to get help quickly. 
@Stokkie64 Thanks very much for the help! I also assume, that he didn't create a directory to keep his data.
-> @afycn: If you need help with this, then I strongly recommend to read/view one of the many publicly available docker-infos about persistent storage or bind-mounts.

I'll close it for now. Feel free to reopen or comment.
