### ISSUE TITLE
Rich text or WYSIWYG?

### ISSUE THREAD

**Issue by thecoffeebin** [PhiTux/DailyTxT#44]
Just installed this today and I love the idea. It's not a replacement for my calendar but it definitely makes a good diary which is searchable.

What I'm mostly missing is the ability to write in rich text format (editor) and paste screenshots/images directly would be awesome!

**Comment by PhiTux** [comment]
First of all: sorry for the late reply. 
Completely oversaw it...

Sadly there is only plaintext supported - look at the begin of the readme. I will not include something different (perhaps in a later rewrite).
