### ISSUE TITLE
Turning off authentication? 

### ISSUE THREAD

**Issue by zodac** [PhiTux/DailyTxT#52]
Is there any way to turn off the login screen? I'd prefer to use my own identity provider, and while something like OIDC is quite a big effort, I was hoping there might be a stick way to disable auth completely?

**Comment by PhiTux** [comment]
Hey, a separate identity provider will (probably) not work, as the password is required to derive a password (PBKDF) for the encryption. And the encryption will always be mandatory.

**Comment by zodac** [comment]
Ahh, shame. I was hoping maybe the encryption key might be separate from the login flow itself, but if they're tied then I guess it'll be too much work to split. Thanks anyway!
