### ISSUE TITLE
BUG(?): User remained logged in after docker reinstall

### ISSUE THREAD

**Issue by antropolouco** [PhiTux/DailyTxT#54]
Hey there! How are you?

Using current public version, I reinstalled using docker composer and for my surprise my test user was still logged in. While tried entering a text, it did not save (just threw a generic error message). I logged out, and the user doesn't exist as expect.

Best regards

**Comment by PhiTux** [comment]
Hi, 
when you're reinstalling and you keep the same secret (as environment variable), then you will stay logged in. 
But in your case it sounds to me, as if this was not really the case. When your frontend made any request to the server (explicitly "save the log"), then the server probably noticed, that you're no longer logged in. 
What's about the content of the users.json file? Is your username still existing there? If yes, then you should be able to login normally. Are you sure, that the file-pathes are correct of your new installation?

**Comment by antropolouco** [comment]
> Hi, when you're reinstalling and you keep the same secret (as environment variable), then you will stay logged in. But in your case it sounds to me, as if this was not really the case. When your frontend made any request to the server (explicitly "save the log"), then the server probably noticed, that you're no longer logged in. What's about the content of the users.json file? Is your username still existing there? If yes, then you should be able to login normally. Are you sure, that the file-pathes are correct of your new installation?

I deleted all the data files, in my case it certainly was the secret key (didn't need to upgrade it, as I was just doing some tests and reinstalled to start using it again. Anyway, when I refreshed the page several times the calendar was open and I was logged in, the user did not exist in the end so any try to edit anything just threw error messages.

I'm actively using DailyTxT now, so let me know when any tests or translations are needed for the next version.

Best regards
