### ISSUE TITLE
[NOT ISSUE] New translation for Spanish language

### ISSUE THREAD

**Issue by SmartPhoneLover** [PhiTux/DailyTxT#6]
I would like to help with the translation of your project ;)

Language: Spanish

Here you have all the related files, from '/client/src/lang'.
es.json
[https://pastebin.com/DXHArvTD](url)
supported-locales.json
[https://pastebin.com/VwMhrftn](url)
index.js
[https://pastebin.com/rs3yV5Qx](url)

**Note**: I have configured all three Pastebins to be deleted automatically in 30 days.

**Comment by PhiTux** [comment]
Thanks very much, it is already merged and will be published within the next days probably :)

**Comment by PhiTux** [comment]
Hi, 
I added some new features now. **Could you translate the new text as well?** 
The spanish translation and the new features will then be published together.
[https://pastebin.com/2tjV4eeK](https://pastebin.com/2tjV4eeK)

Thanks!

**Comment by SmartPhoneLover** [comment]
Translated!
