### ISSUE TITLE
Setting Registration Variable to False Not Working

### ISSUE THREAD

**Issue by twinkie0101** [PhiTux/DailyTxT#7]
Hi, I am running this on Unraid via docker and set the registration to False, but registration is still available.  I also tried removing the variable but registration persists as an option.

The variable in Unraid is setup as follows: 

![image](https://user-images.githubusercontent.com/79336898/151920168-226fb630-bf14-4b0b-a090-4fb4951751c1.png)

Love this BTW! Nice job!

**Comment by PhiTux** [comment]
Are you sure, that registration is really still possible? 
When it is set to False, the form is still visible, yes, but the functionality is switched off and you should get an error-message when trying to register.

**Comment by twinkie0101** [comment]
I am, tried it when set to False and removing the variable entirely, both scenarios allow me to register an account.

**Comment by PhiTux** [comment]
No, I checked it on my installation with docker-compose: Removing the parameter completely or setting it to False results in not being able to register...
Perhaps thats some bug in unraid? I have no idea how that works with the parameters / environment variables...

**Comment by twinkie0101** [comment]
Thanks for trying to help.

**Comment by SmartPhoneLover** [comment]
I tried setting it to 'False' on mine, and it works as described above. (unRAID)

**Comment by PhiTux** [comment]
Great! Thanks for the feedback!
